export const colleges = [
  { name: "Bates Technical College", group: "Bates Technical College" },
  { name: "Bellevue College", group: "Bellevue College" },
  { name: "Bellingham Technical College", group: "Bellingham Technical College" },
  { name: "Big Bend Community College", group: "Big Bend Community College" },
  { name: "Cascadia College", group: "Cascadia College" },
  { name: "Centralia College", group: "Centralia College" },
  { name: "Clark College", group: "Clark College" },
  { name: "Clover Park Technical College", group: "Clover Park Technical College" },
  { name: "Columbia Basin College", group: "Columbia Basin College" },
  { name: "Edmonds College", group: "Edmonds Community College" },
  { name: "Everett Community College", group: "Everett Community College" },
  { name: "Grays Harbor College", group: "Grays Harbor College" },
  { name: "Green River College", group: "Green River College" },
  { name: "Highline College", group: "Highline College" },
  { name: "Lake Washington Institute of Technology", group: "Lake Washington Institute of Technology" },
  { name: "Lower Columbia College", group: "Lower Columbia College" },
  { name: "Northwest Indian College", group: "Northwest Indian College" },
  { name: "Olympic College", group: "Olympic College" },
  { name: "Peninsula College", group: "Peninsula College" },
  { name: "Pierce College", group: "Pierce College" },
  { name: "Renton Technical College", group: "Renton Technical College" },

  { name: "North Seattle College", group: "Seattle Colleges" },
  { name: "Seattle Central College", group: "Seattle Colleges" },
  { name: "South Seattle College", group: "Seattle Colleges" },

  { name: "Shoreline Community College", group: "Shoreline Community College" },
  { name: "Skagit Valley College", group: "Skagit Valley College" },
  { name: "South Puget Sound Community College", group: "South Puget Sound Community College" },

  { name: "Spokane Community College", group: "Community Colleges of Spokane" },
  { name: "Spokane Falls Community College", group: "Community Colleges of Spokane" },

  { name: "Tacoma Community College", group: "Tacoma Community College" },
  { name: "Walla Walla Community College", group: "Walla Walla Community College" },
  { name: "Wenatchee Valley College", group: "Wenatchee Valley College" },
  { name: "Whatcom Community College", group: "Whatcom Community College" },
  { name: "Yakima Valley College", group: "Yakima Valley College" },
];